# TODO: pick node version
image: node:10

stages:
  - setup
  - test

yarn:install:
  stage: setup
  script:
    - yarn install
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - node_modules/
  cache:
    key: ALL
    paths:
      - .yarn-cache/

test:unit:
  stage: test
  script:
    - yarn test
  coverage: '/^Statements\s*:\s*([^%]+)/'
  dependencies:
    - yarn:install
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - coverage/

test:lint:
  stage: test
  script:
    - yarn lint
  dependencies:
    - yarn:install
